version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - postgres
    environment: 
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: production
      PORT: 8000
    ports:
      - "8000:8000"

  postgres:
    image: postgres:12.6
    ports: 
      - "35000:5432"
    environment: 
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: db